# Generated by Django 4.1.7 on 2023-03-24 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ShortenedURL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_url', models.URLField()),
                ('short_token', models.CharField(max_length=6, unique=True)),
                ('clicks', models.IntegerField(default=0)),
            ],
        ),
    ]
